### ISSUE TITLE
Question Regarding Login View

### ISSUE THREAD

**Issue by b4rrtp** [VeeamHub/martini-web#2]
Hi

We want to give a tenant permission to individual organizations only, currently we are only able to give customer access all backups on the veeam host. 

Picture of tenants associated to instances:
![TenantsAssociatedWithInstances](https://user-images.githubusercontent.com/56819362/67759927-a8e5e380-fa40-11e9-9684-fda21c660709.png)

Login Associated to Veeam Host Account:
![FullAtLogonThatHaveAccessToAllOrganizations](https://user-images.githubusercontent.com/56819362/67759152-3fb1a080-fa3f-11e9-83fc-ad3a59c393a3.png)

We have tested vbo365-rest made by nielsengelen earlier with that project we were able to access the restore page with the backup logins but with this project the page will just be empty and no backups can be found on the restore page. 

Login Associated to Backup Account:
![EmptyAtLogonUsingBackupAccount](https://user-images.githubusercontent.com/56819362/67759096-26105900-fa3f-11e9-9598-8fc072660f24.png)

Is there a way to limit what organisations a tenant can see for a specific veeam instance or a way to make veeam backup users access the restore page or the organisation associated to their backup login.

Kind Regards
Rasmus

**Comment by nielsengelen** [comment]
Hi Rasmus, Project Martini is a sort of layer on top of the self-service portal. We added the existing code to see if it would work and with almost no changes to the code, it just worked. There is currently no way of passing through the login of admin@domain.com straight on to the corresponding VBO server. It may be something to look in for a future version. 

The multi-tenant part in Martini is related to the accounts being made within the interface (and gives access to the specific VBO installations connected to the account).
