### ISSUE TITLE
Question about connection on instances

### ISSUE THREAD

**Issue by DaniGarciaCastro** [VeeamHub/martini-web#3]
Hello! 

After having mounted the platform of the Project Martini, I would like to know how I can connect to an instance already created in the local network, that is to say, I have mounted an Office365 in a machine in the same network that the Project Martini, but at the time of giving to connect, it does not connect.

The API parameters (4443) are enabled as you can see in the image:

![image](https://user-images.githubusercontent.com/16239714/89397562-e9793880-d707-11ea-9b1c-6b370827ab3c.png)

![image](https://user-images.githubusercontent.com/16239714/89396963-27299180-d707-11ea-8e59-a4d1a6a55319.png)

I can't find much information about the project, so I'd like to know more.

**Comment by nielsengelen** [comment]
Can you perform a ping to the VBO server from the Project Martini server? If the port is open, it should be able to connect.

**Comment by DaniGarciaCastro** [comment]
Hello, 

Thank you for responding.

Yes, from the martini project server I can ping the VBO server. The port is open and it's a local IP, not a public IP.

I don't know if it is necessary that the servers are hosted in AWS or Azure to be able to configure the Martini Project.

Currently, both servers are in a local network, for testing purposes.

Attached ping image:

![image](https://user-images.githubusercontent.com/16239714/89413124-294c1a00-d720-11ea-8aa0-496a6a11edf4.png)

**Comment by nielsengelen** [comment]
No, this project can run anywhere. AWS/Azure aren't needed. Can u verify [authentication](https://helpcenter.veeam.com/docs/vbo365/guide/vbo_authentication_settings.html?ver=40) is enabled in VBO?

**Comment by DaniGarciaCastro** [comment]
Yes, it's enabled

![image](https://user-images.githubusercontent.com/16239714/89413411-b5f6d800-d720-11ea-94f1-15ad44000308.png)

**Comment by nielsengelen** [comment]
The last thing we can check for now is regarding any firewalls, can u access the RESTful API service on that server on port 4443? You could perform "nmap -p 4443 192.168.11.63" on the project martini server to test this.

The account you can use is the Administrator account from the VBO server.

**Comment by DaniGarciaCastro** [comment]
Here is the nmap:

![image](https://user-images.githubusercontent.com/16239714/89414015-a1ffa600-d721-11ea-8894-b3ae4b9d7bd5.png)

**Comment by DaniGarciaCastro** [comment]
I don't know if this helps, but I think there is something wrong:

![image](https://user-images.githubusercontent.com/16239714/89414469-5ac5e500-d722-11ea-8347-cc13b5b11653.png)

**Comment by nielsengelen** [comment]
That is actually a normal response for the Token reply. Can you drop me an e-mail via niels.engelen@veeam.com - I will have to take a look at some logs or maybe have a remote call.
