### ISSUE TITLE
helpme not install project martini on server veeam backup MS365

### ISSUE THREAD

**Issue by Eduardo69a** [VeeamHub/martini-web#8]
hi I'm new to the whole topic of creating, modifying files, libraries in php. I downloaded all the files of the Martinis project for veeam backup MS 365 and I am getting an error

**To Reproduce**
Warning: require_once(C:\veeammt\core\../config.php): failed to open stream: No such file or directory in C:\veeammt\core\database.php on line 2

Fatal error: require_once(): Failed opening required 'C:\veeammt\core\../config.php' (include_path='.;C:\php\pear') in C:\veeammt\core\database.php on line 2

the files are the originals hung in your tutorial

screenshop
![error](https://user-images.githubusercontent.com/75845055/101912725-85c0b980-3b98-11eb-888e-9b6d7ebf8f6b.JPG)

OS windows server 2012 r2
php 7.2
IIS

helpme please

**Comment by nielsengelen** [comment]
Hi,

In order to install it please follow the installation blog: http://blog.dewin.me/2019/06/installing-project-martini.html 

We have not tested it on Windows, we advise to use Ubuntu Linux to run this project.

Thanks!
